export const SPRINGSHARE_HEADERS = [
  "ID (Required)",
  "DATABASE NAME (Required)",
  "PUBLIC DATABASE DISPLAY",
  "DATABASE LANDING PAGE",
  "DATABASE URL",
  "USE PROXY?",
  "FRIENDLY URL",
  "DATABASE LANDING PAGE FRIENDLY URL",
  "ALTERNATE NAMES",
  "KEYWORDS & MISSPELLINGS",
  "DATABASE DESCRIPTION",
  "VENDOR",
  "TYPES",
  "ASSOCIATED SUBJECTS",
  "BEST BETS",
  "ATTRIBUTES",
  "FLAGS",
  "THUMBNAIL URL",
  "THUMBNAIL ALT TEXT",
  "MORE INFO",
  "LIBRARIAN REVIEW",
  "INTERNAL NOTE",
  "ACCESS MODES",
  "OWNER",
  "RESOURCE ICONS",
  "PERMITTED USES"
] as const;

export const CANONICAL_SUBJECTS = [
  "Accounting and Tax",
  "African American Studies",
  "Aging Studies",
  "American Studies",
  "Anthropology",
  "Archaeological Anthropology",
  "Archaeology",
  "Art",
  "Asian American Studies",
  "Asian Studies",
  "Biological Science",
  "Business",
  "Chemistry & Biochemistry",
  "Chicana & Chicano Studies",
  "Child & Adolescent Studies",
  "Cinema and Television Arts",
  "Communication Sciences and Disorders",
  "Communications",
  "Communications--Advertising",
  "Communications--Entertainment Studies",
  "Communications--Journalism",
  "Communications--Public Relations",
  "Computer Science",
  "Counseling",
  "Criminal Justice",
  "Cultural Anthropology",
  "Dance",
  "Database EBA",
  "Economics",
  "Education",
  "Engineering",
  "English and Comparative Literature",
  "Environmental Studies",
  "Evolutionary Anthropology",
  "Finance",
  "Gender and Sexuality Studies",
  "General Research",
  "Geography and the Environment",
  "Geological Sciences",
  "History",
  "History - United States",
  "Human Communication",
  "Human Services",
  "Instructional Design and Technology",
  "International Business",
  "Kinesiology",
  "Latin American Studies",
  "Liberal Studies",
  "Library and Information Science",
  "Linguistic Anthropology",
  "Linguistics",
  "Management",
  "Marketing",
  "Mathematics",
  "Modern Languages & Literatures",
  "Music",
  "Native American Studies",
  "Nursing",
  "Philosophy",
  "Physics",
  "Political Science",
  "Psychology",
  "Psychology, Counseling, Social Work",
  "Public Health",
  "Queer Studies",
  "Religious Studies",
  "Social Work",
  "Sociology",
  "TESOL",
  "Theatre"
] as const;

export const CHOICE_LABELS = {
  original: "Original description",
  rewritten_a: "Rewritten description A",
  rewritten_b: "Rewritten description B",
  edited: "Edited / revised version",
  needs_follow_up: "Needs follow-up / no recommendation"
} as const;

export const FINAL_DECISION_LABELS = {
  use_original: "Use Original",
  use_rewritten_a: "Use Rewritten A",
  use_rewritten_b: "Use Rewritten B",
  use_faculty_revision: "Use faculty revision",
  custom_final: "Use custom final edited description",
  hold: "Needs additional work / hold"
} as const;
